# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nikte < Formula
  desc "Fast CLI for ephemeral content management"
  homepage "https://github.com/sim4gh/nikte-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.5.0/nikte-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "26051249413215d3be5d4e979c350718fd4c09fa8496a113db163ddeedd77117"

      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.5.0/nikte-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "5e7a4e0e1aab38d030aaa790a0aacd1a1fae4b9cf69c0a7e2e3570417925b63f"

      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.5.0/nikte-cli_0.5.0_linux_amd64.tar.gz"
      sha256 "50b58ed418b5bb2ef7dff194de3079f4a9431ab9144d4000adc2d8e57ff6bf0d"
      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.5.0/nikte-cli_0.5.0_linux_arm64.tar.gz"
      sha256 "aa4b360fdc56753d738882fb56beadaae14c8ca3ec07943521a28464e4aa517d"
      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  test do
    system "#{bin}/nk", "--version"
  end
end
