# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nikte < Formula
  desc "Fast CLI for ephemeral content management"
  homepage "https://github.com/sim4gh/nikte-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.3.0/nikte-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "675bc691a023369fed6960d3b876fcea8c8a19ed01817adedbbd31376b7e7e20"

      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.3.0/nikte-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "00982756c13e025b7d23afdff12bea32507f7255ee4398305a0946fd52974035"

      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.3.0/nikte-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "aa8952f41735d5b2b0d29e2d58b499bb76f2c955b5519d8f8408589d71c0e966"
      define_method(:install) do
        bin.install "nk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sim4gh/nikte-cli/releases/download/v0.3.0/nikte-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "18ca72852e74ee9ae6074708a2db7a862e857387d4d091873851bc48b5bf031f"
      define_method(:install) do
        bin.install "nk"
      end
    end
  end

  test do
    system "#{bin}/nk", "--version"
  end
end
